# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target '星火钱包' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'JPush'
	pod 'Alamofire', '~>4.0.0'
        pod 'RxSwift'
	pod 'RxCocoa'
	pod 'RxDataSources'
	pod 'SnapKit'
#	pod 'PullToRefreshSwift'
  # Pods for 星火钱包

  target '星火钱包Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '星火钱包UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
